### ISSUE TITLE
Drywall crashes on browser navigation to default page; no styling, no error from nodemon

### ISSUE THREAD

**Issue by sanchezelton** [jedireza/drywall#327] opened 2015-11-11 10:22 UTC
I've installed Drywall as per instructions on the README.md file. Here is my `node -v` and `npm -v` output:
```bash
$ node -v
v0.12.7
$ npm -v
2.11.3
```
I've been starting the server with `grunt`, getting this output when using `grunt -v`. It is quite long, so I will just attach it here:

[grunt.out.txt](https://github.com/jedireza/drywall/files/31762/grunt.out.txt)

No errors seemed to be reported to the console, until I point the browser to http://localhost:3000

```grunt
GET / 304 913.808 ms - -
[nodemon] app crashed - waiting for file changes before starting...
```

I'm running on Windows 7, having used git bash and msys bash (I've worked on a few simpler Express projects with no issues). I've also tried running `grunt build` before `grunt`, but I get the same results. Same with `npm start`.

My understanding is that bower is no longer required with Drywall, although I did try installing it using `npm install -g bower`. But without a bower.json file, this is moot.

As far as the browser, it does receiving some output, but it is unstyled. See the screenshot:

![screenshot-localhost 3000 2015-11-11 02-05-12](https://cloud.githubusercontent.com/assets/3165000/11088932/cf02f75c-881a-11e5-9a01-55248bd9bbc0.png)

Here's my `npm version` output:
```javascript
{ Drywall: '0.16.4',
  npm: '2.11.3',
  http_parser: '2.3',
  modules: '14',
  node: '0.12.7',
  openssl: '1.0.1p',
  uv: '1.6.1',
  v8: '3.28.71.19',
  zlib: '1.2.8' }
```

How can I find out what is causing the crash?

**Comment by jedireza** [comment] 2015-11-13 02:54
Thanks for creating an issue. It looks like things are working server side since you're rendering the layout + view. Since the styles are not being applied we need to make sure we're loading the css files. Have you checked your network tab in your browser dev tools?

**Comment by sanchezelton** [comment] 2015-11-13 07:13
Yes, I've only got the following appearing in the Network tab:

![screenshot-localhost 3000 2015-11-12 23-12-xx](https://cloud.githubusercontent.com/assets/3165000/11140736/b25921e8-8992-11e5-87d6-5b254d8e6dad.png)
(ignore the HTTP 200 on core.min.css, the content only reads "Reload the page to get source for: http://localhost:3000/layouts/core.min.css?br34k-01"; I think that was Firebug; Chrome and native Firefox give similar results)

I think there is a server issue because while I can see the six GET requests, only the fetch to localhost:3000/ has a response body (the raw HTML). The rest (JS, CSS, even the GIF) are blank. 

I tried addressing some of the issues by visiting some threads on StackOverflow and GitHub and doing the following:

1. Making changes to Gruntfile.js to catch the crash event; however, the event parameter always returns "undefined" for the "crash" nodemon event (see the function for the callback option for nodemon, lines 67-94; I commented out the stuff related to open because I haven't yet injected a LiveReload script as per https://github.com/ChrisWren/grunt-nodemon, see end of Advanced Usage section).

[Gruntfile.js](https://github.com/jedireza/drywall/files/33665/Gruntfile.js.txt)

2. I also tried adding some entries to packages.json (lines 36-41), as per https://github.com/jedireza/drywall/issues/140 following suggestion from @henchan

[package.json](https://github.com/jedireza/drywall/files/33666/package.json.txt)

**Comment by jedireza** [comment] 2015-11-17 08:31
Sorry for the delay. I haven't had much time to look at this.

Any updates on your end? We need to figure out if the js/css assets are being generated or if there's an issue serving them.

**Comment by sanchezelton** [comment] 2015-11-17 22:42
I ran ```npm start``` and left the server running, then opened new tab in Chrome to localhost:3000, opening web dev tools before I navigate to the page.

I get the error as previously reported, then checked on the status of the files. Here's what I got:

```bash
[~] $ cd dev/learn-nodejs/05-communityEvents/comevents/
[comevents] $ ls
Gruntfile.js      LICENSE    app.js             config.js  models.js     npm-debug.log  package.json.txt  public     schema  views
Gruntfile.js.txt  README.md  config.example.js  layouts    node_modules  package.json   passport.js       routes.js  util
[comevents] $ ls public
favicon.ico  layouts  less  media  vendor  views
[comevents] $ ls public/views/
about  account  admin  contact  index.less  index.min.css  login  signup
[comevents] $ ls public/media
ajax-pulse.gif  logo-symbol-32x32.png  logo-symbol-64x64.png
[comevents] $ ls public/layouts
admin.js    admin.min.css  admin.min.js.map  core.less     core.min.js      ie-sucks.js      ie-sucks.min.js.map
admin.less  admin.min.js   core.js           core.min.css  core.min.js.map  ie-sucks.min.js
```

So the js/css assets are generated, but serving them runs into problems. Even the log confirms it:

```
Running "concurrent:dev" (concurrent) task
    Running "nodemon:dev" (nodemon) task
    Running "watch" task
    Waiting...
    [nodemon] v1.3.8
    [nodemon] to restart at any time, enter `rs`
    [nodemon] ignoring: node_modules/***/* public/***/*
    [nodemon] watching: *.*
    [nodemon] watching extensions: js
    [nodemon] starting `node app.js`
    [nodemon] child pid: 9684
    Server is running on port 3000
    [nodemon] watching 13,570 files
    GET / 200 877.244 ms - -
    Application crashed!
    undefined
    [nodemon] app crashed
```

The 'Application crashed!' and 'undefined' bit is when I try to output the content of the exception for the 'crash' event via console.log(), nothing is passed to the callback. (see Gruntfile.js, lines 72-75, previously posted).

**Comment by jedireza** [comment] 2015-11-19 08:13
Hmm. Have you opened up those `*.min.{js,css}` files and made sure they have content in them? If so, it seems like an asset serving issue, which would be strange.

Also after the asset files are generated with grunt try starting the server without `nodemon` like `$ node app.js` ... if/when the server crashes, you should see a stack trace in your terminal.

More generally, in these cases it's easier to debug if we start limiting our scope by taking pieces away until we find something small we can reproduce.

**Comment by sanchezelton** [comment] 2015-11-20 07:25
Now this is interesting. I tried running ```node app.js``` as you said. I waited until I got the ```Server is running on port 3000``` message, then navigated to localhost:3000 in Chrome.

This was the output:

```
GET / 200 1129.683 ms - -
GET /views/index.min.css?br34k-01 200 11.930 ms - 241
GET /media/logo-symbol-64x64.png 200 17.937 ms - 2651
```
..then node quit, returning me to the prompt. I was hoping for a stack trace, but none appeared. This occured in my Git Bash shell, my msys shell environment, as well as running node from the Windows command prompt as well.

So I decided running the debugger:
```
$ node debug app.js
```

This is what was worked out through some trial and error (I have little experience with a CLI debugger, but it seemed [straightforward](https://nodejs.org/api/debugger.html).
```
< Debugger listening on port 5858
debug> . ok
break in C:\Users\sanchezelton\dev\learn-nodejs\05-communityEvents\comevents\app.js:1
> 1 'use strict';
  2
  3 //dependencies
debug> c
< Server is running on port 3000
debug> breakOnException
[at this point I loaded http://localhost:3000 in chrome]
exception in fs.js:797
Error: ENOENT, no such file or directory 'C:\Users\sanchezelton\dev\learn-nodejs\05-communityEvents\comevents\node_modules\express\lib\node_modules\jade'
program terminated
```

True to the error message, the above directory is not present in my project (the furthest I got was 'node_modules/express/lib'). 

Yet, when I check my package.json (posted earlier), jade is clearly listed under 'dependencies':

```
...
"jade": "^1.x.x",
...
```

So I tried installing jade globally with ```npm install -g jade```. Reran it and no dice.

The funny thing is I can clearly see the jade directory under node_modules/jade.

**Comment by steveupr** [comment] 2015-11-27 16:02
Have you tried running `npm cache clean` to make sure you're not pointing at the other jade package?

**Comment by sanchezelton** [comment] 2015-11-27 21:04
@steveupr OK, I've tried your suggestion, but the issue remains the same. When I tried debugging via ```node debug app.js```, the same error appeared.
```
Error: ENOENT, no such file or directory 'C:\Users\sanchezelton\dev\learn-nodejs\05-communityEvents\comevents\node_modules\express\lib\node_modules\jade'
```

**Comment by jedireza** [comment] 2015-12-03 06:28
Darn, it's a bummer we haven't found what's causing this. I was just about to get a Windows server running on EC2 to try and replicate the issue. Turns out that AWS doesn't support Windows 7. `¯\_(ツ)_/¯`

This may be an edge case or a bug. In cases like this, you may want to try replicating the issue by creating a small spike project that only uses `grunt`, `nodemon`, `express` and `jade` and see if you can replicate this error with the least amount of moving parts as possible. If so we'd be able to reach out to the folks from those projects (where appropriate) with a small example that's easy to reason about. Right now there are too many moving pieces to determine the root cause.

**Comment by sanchezelton** [comment] 2015-12-04 06:39
I'll look for a project that only uses grunt, nodemon, express and jade (or I might make my own, what better way to train). Still, this is a bummer; I'll look for other ways of running this (or possibly using Linux, not sure if that's an option for me at this point).

Even if EC2 does not support Windows 7 natively, is "inceptioning" (VM in a cloud VM instance) an option? E.g. running a Windows 7 instance on VirtualBox on a EC2 Ubuntu instance?

**Comment by jedireza** [comment] 2016-01-19 08:14
Closing for now. Please update this thread if you find more information.

**Closed by jedireza** 2016-01-19 08:14 UTC
Labels: question
