### ISSUE TITLE
451 - bare linefeed issue

### ISSUE THREAD

**Issue by StewartNoyce** [jedireza/drywall#277] opened 2015-03-06 06:56 UTC
I loaded Drywall and created two users in the database.  To set the password through the /forgot view, Drywall sends an email through an account on one of my domains hosted by network solutions. After connection is established and message content is sent, the host responds with "451 See http://pobox.com/~djb/docs/smtplf.html." The referenced page says the mailer sent an email message with a bare lf, meaning no cr included. 

Additionally, this error message came right after the 451.
> smtp connection destroyed!

>http.js:689
    throw new Error('Can\'t set headers after they are sent.');
          ^
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (http.js:689:11)
    at ServerResponse.header (/Users/stewartnoyce/Playground/mend-d3/node_modules/express/lib/response.js:700:10)
    at ServerResponse.send (/Users/stewartnoyce/Playground/mend-d3/node_modules/express/lib/response.js:154:12)
    at ServerResponse.json (/Users/stewartnoyce/Playground/mend-d3/node_modules/express/lib/response.js:240:15)
    at ServerResponse.send (/Users/stewartnoyce/Playground/mend-d3/node_modules/express/lib/response.js:142:21)
    at EventEmitter.<anonymous> (/Users/stewartnoyce/Playground/mend-d3/util/workflow/index.js:23:9)
    at EventEmitter.emit (events.js:92:17)
    at Object.req.app.utility.sendmail.error (/Users/stewartnoyce/Playground/mend-d3/views/login/forgot/index.js:78:18)
    at Object.callback (/Users/stewartnoyce/Playground/mend-d3/util/sendmail/index.js:84:19)
    at connect (/Users/stewartnoyce/Playground/mend-d3/node_modules/emailjs/smtp/client.js:69:19)

Any suggestions on how to get this to work?

**Comment by jedireza** [comment] 2015-03-06 08:55
Would you be willing to share what operating system you're running and also what you get when you run:

```js
$ npm version
```

**Comment by StewartNoyce** [comment] 2015-03-06 16:49
Yes, I am on Mac OS X 10.6.8 (Snow Leopard).  

npm version generates

{ http_parser: '1.0',
  node: '0.10.32',
  v8: '3.14.5.9',
  ares: '1.9.0-DEV',
  uv: '0.10.28',
  zlib: '1.2.3',
  modules: '11',
  openssl: '1.0.1i',
  npm: '1.4.28' }

One last thing, I changed systemEmail and smtp.credentials.from.address to use an earthlink account of mine.  That works!  I don't want to use that account, but I share it as a clue.

**Comment by jedireza** [comment] 2015-03-07 04:59
Actually it looks like this may be an `emailjs` issue. You may like to try reproducing the error with emailjs in a gist and [adding it to the issue you created there](https://github.com/eleith/emailjs/issues/118).

I'll close this issue for now. Let's re-open this if you find out that the error is in Drywall code.

**Closed by jedireza** 2015-03-07 04:59 UTC
Labels: question
